# Generated by Django 5.1.1 on 2024-11-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gguser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/profile_pics/default.png', null=True, upload_to='media/profile_pics/'),
        ),
    ]
