# Generated by Django 5.1.1 on 2024-11-23 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_gguser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Spamming or harassment', 'Spamming or harassment'), ('This user is a bot', 'This user is a bot'), ('This Product is not delivered on time', 'This Product is not delivered on time'), ('Posting copyrighted product', 'Posting copyrighted product'), ('Posting illegal product', 'Posting illegal product')], max_length=60)),
                ('report_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Resolved', 'Resolved'), ('Dismissed', 'Dismissed')], default='Pending', max_length=20)),
                ('date_filed', models.DateTimeField(auto_now_add=True)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reported_user', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_report_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
