# Generated by Django 5.1.1 on 2024-11-24 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_category'),
        ('users_app', '0004_report_reported_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reported_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reported_product', to='products.product'),
        ),
    ]
