# Generated by Django 5.1.1 on 2024-12-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_gguser_ban_end_date_gguser_ban_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='gguser',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
    ]
