# Generated by Django 5.1.1 on 2024-12-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0007_gguser_birth_date_gguser_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gguser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
