# Generated by Django 5.1.1 on 2024-12-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingpoint',
            name='seller_name',
            field=models.CharField(default='Unknown Seller', max_length=100),
        ),
        migrations.AlterField(
            model_name='meetingpoint',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meetingpoint',
            name='pickup_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meetingpoint',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
